import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import utilStyles from "./utils.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Next.js Blog",
    default: "Next.js Blog",
  },
  description: "Generated by create next app",
};

const name = "Rumi's Blog"

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={styles.container}>
        <header className={styles.header}>
          <Image src="/images/profile.jpg" alt="Site logo" width={100} height={100} className={utilStyles.borderCircle}/>
          <h1 className={utilStyles.heading2Xl}>{name}</h1>
        </header>
        {children}
        </body>
    </html>
  );
}